embeddings:
  model: 'distilbert'
  tokenizer:
    max_length: 128
    padding: 'max_length'
    truncation: True
  dataloader:
    batch_size: 256
    num_workers: 4
    pin_memory: True
    shuffle: False
    drop_last: False
  non_blocking: True
